# Generated by Django 5.0.1 on 2024-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_alter_customer_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_profile',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
